// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Counter: typeof import('./components/Counter.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    ICarbonBasketball: typeof import('~icons/carbon/basketball')['default']
    ICarbonChat: typeof import('~icons/carbon/chat')['default']
    ICarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    ICarbonEducation: typeof import('~icons/carbon/education')['default']
    ICarbonEmail: typeof import('~icons/carbon/email')['default']
    ICarbonHome: typeof import('~icons/carbon/home')['default']
    ICarbonMoon: typeof import('~icons/carbon/moon')['default']
    ICarbonPedestrian: typeof import('~icons/carbon/pedestrian')['default']
    ICarbonSun: typeof import('~icons/carbon/sun')['default']
    ICarbonTranslate: typeof import('~icons/carbon/translate')['default']
    ICarbonWarning: typeof import('~icons/carbon/warning')['default']
    ICibFacebook: typeof import('~icons/cib/facebook')['default']
    ICibInstagram: typeof import('~icons/cib/instagram')['default']
    ICibLine: typeof import('~icons/cib/line')['default']
    IMdiCodeJson: typeof import('~icons/mdi/code-json')['default']
    IMdiCreation: typeof import('~icons/mdi/creation')['default']
    IMdiFaceMan: typeof import('~icons/mdi/face-man')['default']
    IMdiHeartPulse: typeof import('~icons/mdi/heart-pulse')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
  }
}

export { }
